default: &default
  adapter: sqlserver
  host: localhost
  username: consumer
  password: DecoProteste09!!
  database: consumer_database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: consumer_database

test:
  <<: *default
  database: consumer_database

production:
  <<: *default
  database: consumer_database
  username: <your_production_username>
  password: <your_production_password>
