development:
  clients:
    default:
      database: consumer_mongo_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
        connect_timeout: 5
        max_pool_size: 5

test:
  clients:
    default:
      database: consumer_mongo_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
        connect_timeout: 5
        max_pool_size: 5
